version: 2.1
orbs:
  elixir: membraneframework/elixir@1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
      - elixir/test:
          filters:
            <<: *filters
      - elixir/lint:
          filters:
            <<: *filters
